"use client";

import React from "react";
import { cn } from "@/lib/utils";
import { ReaderConfig } from "../shared/ReaderHeader";
import { InspectionIssue } from "@/lib/types";
import { Chapter } from "@/lib/db";

interface ParagraphData {
    id: string;
    text: string;
    isHighlighted: boolean;
    issues: InspectionIssue[];
}

interface ReaderContentProps {
    activeTab: "translated" | "original";
    isParallel: boolean;
    readerConfig: ReaderConfig;
    chapter: Chapter;
    inspectionIssues: InspectionIssue[];
    activeTTSIndex: number | null;
    paragraphsData: ParagraphData[];
    setEditContent: (content: string) => void;
    isEditing: boolean;
    // Handlers
    handleTextSelection: () => void;
    handleContextMenu: (e: React.MouseEvent) => void;
    setActiveIssue: (issue: InspectionIssue | null) => void;
    // Refs
    scrollViewportRef: React.RefObject<HTMLDivElement | null>;
    editorRef: React.RefObject<HTMLDivElement | null>;
    // Scroll Handlers
    handleScroll: (e: React.UIEvent<HTMLDivElement>) => void;
    handleWheel: (e: React.WheelEvent<HTMLDivElement>) => void;
    // Navigation
    onNext?: () => void;
    hasNext?: boolean;
}

import { useRaiden } from "@/components/theme/RaidenProvider";

const ParagraphItem = React.memo(({
    para,
    index,
    isRaidenMode,
    showDialogueLines,
    readerConfig
}: {
    para: ParagraphData,
    index: number,
    isRaidenMode: boolean,
    showDialogueLines: boolean,
    readerConfig: ReaderConfig
}) => {
    const isHighlighted = para.isHighlighted;
    const cleanText = para.text.trim();

    const isDialogue = cleanText.startsWith("“") ||
        cleanText.startsWith("\"") ||
        cleanText.startsWith("「") ||
        cleanText.startsWith("『") ||
        cleanText.startsWith("-") ||
        cleanText.startsWith("–") ||
        cleanText.startsWith("—");

    const renderContent = () => {
        let text = para.text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

        // Restore common safe tags that might be generated by AI or formatting
        text = text.replace(/&lt;br\s*\/?&gt;/gi, "<br/>");
        text = text.replace(/&lt;b&gt;(.*?)&lt;\/b&gt;/gi, "<b>$1</b>");
        text = text.replace(/&lt;i&gt;(.*?)&lt;\/i&gt;/gi, "<i>$1</i>");

        // ✨ Intelligent Dialogue Highlighting: Only italicize the part INSIDE the quotes if it's a mix
        if (isDialogue && !isRaidenMode) {
            // Regex to match text inside curly quotes: “...”
            text = text.replace(/(“.*?”)/g, '<i class="not-italic text-[hsl(var(--dialogue-text))] opacity-100">$1</i>');
            // If it starts with - or — (traditional style), we might still want to italicize the whole line if it's short
            if (para.text.startsWith("-") || para.text.startsWith("—")) {
                text = `<i class="text-[hsl(var(--dialogue-text))]">${text}</i>`;
            }
        }

        para.issues.forEach(issue => {
            if (!issue.original) return;
            const regex = new RegExp(issue.original.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
            // Subtle AI Underline: Low opacity by default, bright on hover
            text = text.replace(regex, `<span class="border-b border-rose-400/20 hover:border-rose-400 hover:bg-rose-400/10 transition-all cursor-help" data-issue-original="${issue.original}">${issue.original}</span>`);
        });

        return { __html: text };
    };

    return (
        <p
            id={`tts-para-${index}`}
            className={cn(
                "mb-(--reader-paragraph-spacing) transition-all duration-300 rounded-sm px-4 py-1 -mx-4 border border-transparent antialiased",
                // Option: Only indent if narrative OR if user explicitly wants it
                readerConfig.indentText && !isDialogue && "indent-8",
                "hover:cursor-text",
                isDialogue && !isRaidenMode && showDialogueLines && "border-l-2 border-l-[hsl(var(--dialogue-quote-border))]",
                isHighlighted
                    ? (isRaidenMode ? "bg-purple-500/10 border-purple-500/20" : "bg-blue-50/60 border-blue-200/50 shadow-xs")
                    : (isRaidenMode ? "hover:bg-slate-800/10" : "hover:bg-slate-50/20")
            )}
            style={{
                lineHeight: readerConfig.lineHeight
            }}
            dangerouslySetInnerHTML={renderContent()}
        />
    );
});

ParagraphItem.displayName = "ParagraphItem";

export const ReaderContent = React.memo(function ReaderContent({
    activeTab, isParallel, readerConfig, chapter,
    inspectionIssues, paragraphsData, setEditContent,
    isEditing,
    handleTextSelection, handleContextMenu, setActiveIssue,
    scrollViewportRef, editorRef,
    handleScroll, handleWheel,
    onNext, hasNext
}: ReaderContentProps) {
    const { isRaidenMode } = useRaiden();

    const finalBgColor = isRaidenMode ? "#0F172A" : readerConfig.backgroundColor;
    const finalTextColor = isRaidenMode ? "#CBD5E1" : readerConfig.textColor;

    return (
        <div
            ref={scrollViewportRef}
            onScroll={handleScroll}
            onWheel={handleWheel}
            className="flex-1 h-full overflow-y-auto custom-scrollbar reader-content-area p-0 select-text"
            style={{ backgroundColor: finalBgColor }}
        >
            <div
                className={cn(
                    "min-h-full",
                    isParallel && (isRaidenMode ? "grid grid-cols-2 divide-x divide-slate-800" : "grid grid-cols-2 divide-x divide-border")
                )}
                style={{ backgroundColor: finalBgColor }}
            >
                {(activeTab === 'original' || isParallel) && (
                    <div className={cn(
                        "min-h-full p-8 md:p-12 pb-20 border-r flex flex-col items-center",
                        isRaidenMode ? "border-slate-800/50" : "border-border/50 bg-slate-50/30"
                    )}>
                        <div className="w-full" style={{ maxWidth: isParallel ? "none" : (readerConfig.maxWidth >= 1400 ? "none" : `${readerConfig.maxWidth}px`) }}>
                            {isParallel && (
                                <div className="mb-8 text-[10px] font-black opacity-40 uppercase tracking-[0.3em] flex items-center gap-2"
                                    style={{ color: isRaidenMode ? "#94A3B8" : "hsl(var(--muted-foreground))" }}>
                                    <div className="w-8 h-px bg-current opacity-20" /> Bản gốc (Trung)
                                </div>
                            )}
                            <div className="leading-relaxed select-text antialiased transition-opacity duration-700"
                                style={{
                                    fontFamily: "'Noto Sans SC', sans-serif",
                                    fontSize: `${readerConfig.fontSize}px`,
                                    lineHeight: readerConfig.lineHeight,
                                    fontWeight: isRaidenMode ? 400 : 500,
                                    textAlign: readerConfig.textAlign,
                                    color: "currentColor",
                                    opacity: isParallel ? 0.4 : 0.8
                                }}>
                                {chapter.content_original?.replace(/<br\s*\/?>/gi, '\n').split(/\n+/).map(p => p.trim()).filter(p => p.length > 0).map((p, i) => (
                                    <p key={i} className="mb-[var(--reader-paragraph-spacing)]">
                                        {p}
                                    </p>
                                ))}
                            </div>
                        </div>
                    </div>
                )}

                {(activeTab === 'translated' || isParallel) && (
                    <div className="min-h-full flex flex-col relative" style={{ backgroundColor: finalBgColor }}>
                        {isParallel && (
                            <div className={cn(
                                "px-8 md:px-12 pt-8 text-xs font-black uppercase tracking-[0.2em] shrink-0",
                                isRaidenMode ? "text-purple-400" : "text-primary/50"
                            )}>Translation</div>
                        )}

                        <div className="relative animate-in fade-in duration-1000 slide-in-from-bottom-4">
                            <div className={cn(
                                "font-bold text-4xl mb-12 text-center antialiased",
                                "mx-auto px-6",
                                "drop-shadow-sm transition-all duration-500",
                                isRaidenMode ? "text-slate-100" : "text-gray-900",
                                isParallel ? "pt-6" : "pt-16 md:pt-24"
                            )}
                                style={{
                                    fontFamily: readerConfig.fontFamily,
                                    maxWidth: isParallel ? "none" : (readerConfig.maxWidth >= 1400 ? "none" : `${readerConfig.maxWidth}px`)
                                }}
                            >
                                {(chapter.title_translated || chapter.title).normalize('NFC')}
                            </div>
                        </div>

                        <div
                            contentEditable={isEditing}
                            suppressContentEditableWarning
                            onInput={(e) => setEditContent(e.currentTarget.innerText)}
                            onSelect={handleTextSelection}
                            onContextMenu={handleContextMenu}
                            className={cn(
                                "w-full flex-1 bg-transparent focus:outline-none outline-none",
                                "mx-auto px-8 pb-4 transition-all duration-500 animate-in fade-in duration-700"
                            )}
                            style={{
                                fontFamily: readerConfig.fontFamily,
                                fontSize: `${readerConfig.fontSize}px`,
                                lineHeight: readerConfig.lineHeight,
                                color: finalTextColor,
                                textAlign: readerConfig.textAlign,
                                maxWidth: isParallel ? "none" : (readerConfig.maxWidth >= 1400 ? "none" : `${readerConfig.maxWidth}px`)
                            }}
                            spellCheck={false}
                            ref={editorRef}
                            onClick={(e) => {
                                const target = e.target as HTMLElement;
                                const issueOriginal = target.getAttribute('data-issue-original');
                                if (issueOriginal) {
                                    const issue = inspectionIssues.find(i => i.original === issueOriginal);
                                    if (issue) setActiveIssue(issue);
                                }
                            }}
                        >
                            {paragraphsData.map((para, index) => (
                                <ParagraphItem
                                    key={para.id}
                                    para={para}
                                    index={index}
                                    isRaidenMode={isRaidenMode}
                                    showDialogueLines={readerConfig.showDialogueLines}
                                    readerConfig={readerConfig}
                                />
                            ))}
                        </div>

                        {/* ZEN DIVIDER - Visual Chapter End Marker */}
                        <div className="flex items-center justify-center py-20 opacity-20 select-none animate-in fade-in zoom-in duration-1000"
                            style={{ maxWidth: isParallel ? "none" : (readerConfig.maxWidth >= 1400 ? "none" : `${readerConfig.maxWidth}px`), margin: "0 auto" }}>
                            <div className="flex gap-6">
                                <div className="w-1.5 h-1.5 rounded-full bg-current" />
                                <div className="w-1.5 h-1.5 rounded-full bg-current" />
                                <div className="w-1.5 h-1.5 rounded-full bg-current" />
                            </div>
                        </div>

                        {/* Explicit Next Chapter Navigation */}
                        <div className="mx-auto px-8 pb-32 w-full flex items-center justify-center"
                            style={{ maxWidth: isParallel ? "none" : (readerConfig.maxWidth >= 1400 ? "none" : `${readerConfig.maxWidth}px`) }}>
                            {hasNext ? (
                                <button
                                    onClick={onNext}
                                    className={cn(
                                        "group relative inline-flex items-center justify-center px-8 py-4 font-bold transition-all duration-200 rounded-full hover:scale-105 hover:shadow-lg focus:outline-none ring-offset-background focus:ring-2 focus:ring-ring focus:ring-offset-2 antialiased",
                                        isRaidenMode ? "bg-purple-600 text-white hover:bg-purple-500 shadow-purple-900/40" : "bg-primary text-white hover:bg-primary/90"
                                    )}
                                    style={{ fontFamily: "'Inter', system-ui, -apple-system, sans-serif", letterSpacing: "0.01em" }}
                                >
                                    <span>Chương Tiếp Theo &rarr;</span>
                                    <div className="absolute inset-0 rounded-full ring-2 ring-white/20 group-hover:ring-white/40 transition-all" />
                                </button>
                            ) : (
                                <div className={cn("italic antialiased", isRaidenMode ? "text-slate-600" : "text-muted-foreground/50")} style={{ fontFamily: "'Inter', system-ui, sans-serif" }}>Hết chương</div>
                            )}
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
});
